### ISSUE TITLE
Black screen on iq-activity on Ubuntu 22.04/Trisquel 11.0

### ISSUE THREAD

**Issue by Ark74** [sugarlabs/iq-activity#21]
Hello!
I keep testing activities for Trisquel 11.0,
I've found that iq-activity shows a black screen when running he activity, could it be that I'm missing some dependency?

Here the log I get,
```
1657067626.554706 ERROR dbus.connection: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sugar3/datastore/datastore.py", line 61, in __datastore_created_cb
    metadata = _get_data_store().get_properties(object_id, byte_arrays=True)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/carquinyol/datastore.py", line 483, in get_properties
    metadata = self._metadata_store.retrieve(uid)
  File "/usr/lib/python3/dist-packages/carquinyol/metadatastore.py", line 79, in retrieve
    metadata = metadatareader.retrieve(metadata_path, properties)
ValueError: Failed to convert metadata value to bytes

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/_propertyhelper.py", line 401, in obj_set_property
    prop.fset(self, value)
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 612, in set_active
    self.save()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 978, in save
    self.write_file(file_path)
  File "/usr/share/sugar/activities/IQ.activity/activity.py", line 68, in write_file
    self.game.save(f)
  File "/usr/share/sugar/activities/IQ.activity/IQ.py", line 110, in save
    f.write(str(self.solved)+'\n')
AttributeError: 'IQ' object has no attribute 'solved'
```
![iq-activity](https://user-images.githubusercontent.com/7444518/177440241-80c7a8ce-e9d3-42a9-a522-21bfa05377e2.png)

Any advice is welcome, regards.

**Comment by quozl** [comment]
Thanks.  I fixed this in https://github.com/sugarlabs/sugar-datastore/commit/df4f45697d07a49cbdd2fcd0c90fbaebf3c539ab so please upgrade to Sugar 0.119

**Comment by Ark74** [comment]
Thanks, I will look forward upgrade.

**Comment by Ark74** [comment]
Hello again,

I'm testing the upgrade to 0.119, and yet I keep having the same behavior

I've confirmed that 0.119 has the change mentioned above.

The error complains only on one issue now,
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/_propertyhelper.py", line 401, in obj_set_property
    prop.fset(self, value)
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 612, in set_active
    self.save()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 978, in save
    self.write_file(file_path)
  File "/usr/share/sugar/activities/IQ.activity/activity.py", line 68, in write_file
    self.game.save(f)
  File "/usr/share/sugar/activities/IQ.activity/IQ.py", line 110, in save
    f.write(str(self.solved)+'\n')
AttributeError: 'IQ' object has no attribute 'solved'
```

**Comment by Ark74** [comment]
Could we re-open this?

**Comment by quozl** [comment]
I don't get the AttributeError, but I'll re-open for that to be worked by someone.  On the blank screen, this is affecting all activities that depend on Pygame,  https://github.com/sugarlabs/sugargame/issues/14 created.

**Comment by rubenquidam** [comment]
The "solved" attribute problem happens because self.solved is not defined at the time it is being accessed. Moving the definition to an earlier step in the constructor removes the error, but the activity still doesn't work. Just a back screen and clicking on the activity button closes the activity. Nothing appears in the log anymore. Other pygame activities work fine. This can be tested with https://cdbuilds.trisquel.org/trisquel-sugar_11.0_amd64.iso

**Comment by quozl** [comment]
Thanks for working on this.

The attribute problem is likely to be caused by the Sugargame issue.  If you've time to work this, please concentrate on the Sugargame issue.  If there are other Sugargame activities that work for you, please update the issue.  Thanks!

Otherwise, if Iq is the only affected activity, close the Sugargame issue, as it was a mistaken analysis.  I don't have a list of what other Sugargame activities were affected in my tests.

If only Iq is affected, then the next guess is that the way Iq calls Sugargame is not compliant with the Sugargame documentation.  I've seen so many ways an activity can be non-compliant, it would not surprise me to find another.
